services:
  f1:
    build: .
    environment:
      TMDB_TOKEN: $TMDB_TOKEN
      BOT_TOKEN: $BOT_TOKEN
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
    command: node app.js
