services:
  filmbot:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      DATABASE_URL: $DATABASE_URL
      SUDO: $SUDO
      SESSION_NAME: $SESSION_NAME
      GAY_USER: $GAY_USER
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
    command: python3 iftarsahur_bot.py
