services:
  b2:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN  
      TMDB_TOKEN: $TMDB_TOKEN  
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
    command: node app.js
